### ISSUE TITLE
Port mopidy-youtube to Python 3

### ISSUE THREAD

**Issue by jodal** [natumbri/mopidy-youtube#116]
Tracking issue for the porting of this extension to Python 3.

**Comment by natumbri** [comment]
@yensa, @jaminh, as you've heard, the mopidy-youtube repository has been transferred to me.  I had already started work on updating the extension and porting it over to python3.  For that reason it didn't make sense to merge in the PRs you submitted.  @staberinde, I notice you also have created a python3 compatible version of the plugin.

Now that the repository has been transferred over, it would be really great if you could test the current version and let me know if you have any comments.  It should work with python 3 - I'm currently using it.

If you know anything about designing tests, or how CI works, I could really use a bit of help in that regard - I have no idea, really.

Really appreciate your earlier contributions, and look forward to anything further you might care to add!

**Comment by jaminh** [comment]
@natumbri, I tried running tox on your branch from your pull request https://github.com/natumbri/mopidy-youtube/pull/115 but was running into some errors. I tried updating it to get tests passing with my best guess at what the tests were trying to accomplish. You can look at what I did here https://github.com/jaminh/mopidy-youtube/tree/natumbri-115. If you want me to clean that up and submit a pull request against your dev branch I can do that. Let me know if there is anything else I can do to help.

**Comment by natumbri** [comment]
Hey @jaminh thanks so much - that's a great start. I reckon tidy that stuff up and submit a PR against develop.  

Perhaps don't take out the commented lines - I haven't decided what to do with them yet.

Have you tried to use the extension? Does it work for you? 

Thanks again for your help!

**Comment by jaminh** [comment]
I submitted a PR and put the commented code back in, but if I might make a friendly suggestion checking in commented code like that is generally frowned upon so I would recommend just moving that code to a separate branch while you are working on it. I'll try actually testing the extension tonight and let you know how it goes.

**Comment by natumbri** [comment]
@jaminh thanks for he PR (which I've merged) and for the suggestion - you are absolutely right: I should (and will) tidy the comments up. Perhaps I will open a couple of issues so I don't forget what I was doing (and so others can contribute).

Thanks again, and good luck with the testing.

**Comment by natumbri** [comment]
mopidy-youtube 3.0a1 is on PyPI. I'm reluctant to bump it past alpha without testing and comments from the real world.

**Comment by natumbri** [comment]
Thanks @jaminh - that looks like a proper bug to squash! 

I think the first step to getting it fixed will be to try to make it reproducible. 

I'll open an issue - it would be really useful if you could then add the information (about your configuration, and the searches that cause this error) necessary to make it reproducible.

Thanks again - your feedback is really valuable!

**Comment by vladmyr** [comment]
Hello! Is there a chance to have it complete in near future? Currently, judging by `mopidyctl deps` it seems that Mopidy doesn't recognize the extension at all therefore I am wondering whether it is because the issue is not yet resolved or because I might have messed up the installation?

**Comment by natumbri** [comment]
Hi @vladmyr - the extension has been ported and should be working fine. Perhaps it is an installation problem? Did you install from pypi:
```
pip install Mopidy-YouTube
```
It should just work ...

**Comment by kingosticks** [comment]
We suggest the following to ensure it's installed under Python 3 and visible to the Mopidy system service:
```
`sudo python3 -m pip install Mopidy-YouTube
```

**Comment by natumbri** [comment]
Thanks @kingosticks - that's *excellent* advice, and not obvious!
