### ISSUE TITLE
Live Videos not working

### ISSUE THREAD

**Issue by tryinit6** [natumbri/mopidy-youtube#146]
Tried to play several live videos.... without success....freezing by "Downloading MPD manifest"

INFO     2020-05-29 21:46:50,681 [859:YouTubeBackend-3] mopidy_youtube
  youtube LibraryProvider.lookup "yt:https://www.youtube.com/watch?v=IiCpDP0zclY"
DEBUG    2020-05-29 21:46:50,718 [859:Thread-28] urllib3.connectionpool
  Resetting dropped connection: www.youtube.com[youtube] IiCpDP0zclY: Downloading webpage

DEBUG    2020-05-29 21:46:51,056 [859:Thread-28] urllib3.connectionpool
  https://www.youtube.com:443 "GET /results?search_query=%22IiCpDP0zclY%22&sp=EgIQAQ%253D%253D&app=desktop&persist_app=1 HTTP/1.1" 200 None
ERROR    2020-05-29 21:46:51,605 [859:Thread-28] mopidy_youtube
  list_videos error "'NoneType' object has no attribute 'text'"
INFO     2020-05-29 21:46:51,608 [859:YouTubeBackend-3] pykka
  Exception returned from YouTubeBackend (urn:uuid:57f12d38-5774-4320-ba52-775eeb11d50c) to caller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 193, in lookup
    name=video.title.get().replace(";", ""),
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR    2020-05-29 21:46:51,610 [859:Core-11] mopidy.core.library
  YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
    result = future.get()
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 193, in lookup
    name=video.title.get().replace(";", ""),
AttributeError: 'NoneType' object has no attribute 'replace'
DEBUG    2020-05-29 21:46:51,614 [859:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.178.20: '{"jsonrpc": "2.0", "id": 47, "result": []}'
[youtube] IiCpDP0zclY: Downloading m3u8 information
[youtube] IiCpDP0zclY: Downloading MPD manifest

**Comment by natumbri** [comment]
Sorry @tryinit6 - didn't mean to close that!  Looks like a problem caused by live videos not having any time.  I pushed something to develop that works around that; let me know if it helps.  

With the changes, I was able to play `IiCpDP0zclY` (`Café del Mar• Chillout Radio & Ibiza Webcam • Live Stream 24/7`)

**Comment by natumbri** [comment]
Sorry @tryinit6 - didn't mean to close that!  Looks like a problem caused by live videos not having any time.  I pushed something to develop that works around that; let me know if it helps.  

With the changes, I was able to play `IiCpDP0zclY` (`Café del Mar• Chillout Radio &amp; Ibiza Webcam • Live Stream 24/7`)

**Comment by tryinit6** [comment]
Yes, perfect! I can confirm this solves the issue, tested with some live stations around. Thanks a lot!

**Comment by natumbri** [comment]
Great - thanks for raising the issue and for the feedback.

**Comment by SSorinC** [comment]
Hello, I encountered an issue when I try to listen the same live video. (IiCpDP0zclY).
So, when I play that youtube link, the song is played only for 5 seconds, then i have this error: Jun 14 17:25:34 pimusic.local mopidy[539]: OverflowError: Python int too large to convert to C long.
My config file is standard, not changed.
[youtube]
enabled = true

I will attach the log with the error.
[mopidy-live-video-log.txt](https://github.com/natumbri/mopidy-youtube/files/4776586/mopidy-live-video-log.txt)

**Comment by agneevX** [comment]
This does not fix the issue and still causes mopidy to crash.

I installed the repo via

```
sudo python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```

<details><summary>Install logs</summary>

```bash
agneev@pi4:~ $ sudo python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
  Downloading https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
     | 1.8 MB 348 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: Mopidy>=3.0 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (3.0.2)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (2.20.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (4.7.1)
Requirement already satisfied, skipping upgrade: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (2.0.2)
Requirement already satisfied, skipping upgrade: cachetools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (4.1.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (49.6.0)
Requirement already satisfied, skipping upgrade: youtube-dl>=2020.5.3 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (2020.5.29)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (1.24.3)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.0) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (2.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (2019.9.11)
Building wheels for collected packages: Mopidy-YouTube
  Building wheel for Mopidy-YouTube (PEP 517) ... done
  Created wheel for Mopidy-YouTube: filename=Mopidy_YouTube-3.0-py3-none-any.whl size=26496 sha256=5745bbd2268c334004678790b6494cac7a23de8dc93c0e556ca64fddf645744e
  Stored in directory: /root/.cache/pip/wheels/df/39/be/50ca706b25181d65718e048da24ae7e1101fef579bdcc8ea63
Successfully built Mopidy-YouTube
Installing collected packages: Mopidy-YouTube
  Attempting uninstall: Mopidy-YouTube
    Found existing installation: Mopidy-YouTube 3.0
    Uninstalling Mopidy-YouTube-3.0:
      Successfully uninstalled Mopidy-YouTube-3.0
Successfully installed Mopidy-YouTube-3.0
agneev@pi4:~ $ sudo systemctl restart mopidy
```

</details>

<details><summary>Crash logs</summary>

```bash
Sep  2 18:09:27 pi4 systemd[1]: Starting Mopidy music server...
Sep  2 18:09:27 pi4 systemd[1]: Started Mopidy music server.
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.config Loading config from command line options
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.__main__ Enabled extensions: http, file, iris, stream, mpd, m3u, youtube, softwaremixer
Sep  2 18:09:28 pi4 mopidy[6292]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: YouTubeBackend, FileBackend, M3UBackend, StreamBackend
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [YouTubeBackend-3] mopidy_youtube using bs4API
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink"
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: YouTubeAutoplayer, IrisFrontend, HttpFrontend, MpdFrontend
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [IrisFrontend-9] mopidy_iris.core Starting Iris 3.52.4
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [HttpFrontend-11] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:127.0.0.1]:6600
Sep  2 18:09:29 pi4 mopidy[6292]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Sep  2 18:09:31 pi4 mopidy[6292]: ERROR    [HttpServer] mopidy_iris.core Connection "0KDWK0EX8HRO" not found
Sep  2 18:09:43 pi4 mopidy[6292]: INFO     [MpdSession-13] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:53480
Sep  2 18:09:47 pi4 mopidy[6292]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.lookup "yt:http://www.youtube.com/watch?v=5qap5aO4i9A"
Sep  2 18:09:47 pi4 mopidy[6292]: INFO     [Thread-15] mopidy_youtube session.get triggered: list_videos (experimental)
Sep  2 18:09:48 pi4 mopidy[6292]: [youtube] 5qap5aO4i9A: Downloading webpage
Sep  2 18:09:48 pi4 mopidy[6292]: INFO     [Thread-15] mopidy_youtube nothing in the soup, trying japi
Sep  2 18:09:49 pi4 mopidy[6292]: [youtube] 5qap5aO4i9A: Downloading m3u8 information
Sep  2 18:09:49 pi4 mopidy[6292]: [youtube] 5qap5aO4i9A: Downloading MPD manifest
Sep  2 18:09:53 pi4 mopidy[6292]: --- Logging error ---
Sep  2 18:09:53 pi4 mopidy[6292]: Traceback (most recent call last):
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_japi.py", line 105, in json_to_items
Sep  2 18:09:53 pi4 mopidy[6292]:     duration_text = content[base]["lengthText"]["simpleText"]
Sep  2 18:09:53 pi4 mopidy[6292]: KeyError: 'lengthText'
Sep  2 18:09:53 pi4 mopidy[6292]: During handling of the above exception, another exception occurred:
Sep  2 18:09:53 pi4 mopidy[6292]: Traceback (most recent call last):
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
Sep  2 18:09:53 pi4 mopidy[6292]:     msg = self.format(record)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
Sep  2 18:09:53 pi4 mopidy[6292]:     return fmt.format(record)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
Sep  2 18:09:53 pi4 mopidy[6292]:     record.message = record.getMessage()
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
Sep  2 18:09:53 pi4 mopidy[6292]:     msg = msg % self.args
Sep  2 18:09:53 pi4 mopidy[6292]: TypeError: not all arguments converted during string formatting
Sep  2 18:09:53 pi4 mopidy[6292]: Call stack:
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
Sep  2 18:09:53 pi4 mopidy[6292]:     self._bootstrap_inner()
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Sep  2 18:09:53 pi4 mopidy[6292]:     self.run()
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Sep  2 18:09:53 pi4 mopidy[6292]:     self._target(*self._args, **self._kwargs)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/youtube.py", line 558, in worker
Sep  2 18:09:53 pi4 mopidy[6292]:     f(*args)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/youtube.py", line 212, in job
Sep  2 18:09:53 pi4 mopidy[6292]:     data = cls.api.list_videos([x.id for x in sublist])
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_bs4api.py", line 307, in list_videos
Sep  2 18:09:53 pi4 mopidy[6292]:     for r in rs
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_bs4api.py", line 308, in <listcomp>
Sep  2 18:09:53 pi4 mopidy[6292]:     for result in cls.run_search(r)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_bs4api.py", line 66, in run_search
Sep  2 18:09:53 pi4 mopidy[6292]:     return jAPI.json_to_items(cls, result_json)
Sep  2 18:09:53 pi4 mopidy[6292]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_japi.py", line 111, in json_to_items
Sep  2 18:09:53 pi4 mopidy[6292]:     logger.warn("no video-time, possibly live: ", e)
Sep  2 18:09:53 pi4 mopidy[6292]: Message: 'no video-time, possibly live: '
Sep  2 18:09:53 pi4 mopidy[6292]: Arguments: (KeyError('lengthText'),)
Sep  2 18:09:53 pi4 mopidy[6292]: INFO     [YouTubeBackend-3] mopidy_youtube youtube PlaybackProvider.translate_uri "youtube:video/lofi hip hop radio - beats to relaxstudy to.5qap5aO4i9A"
Sep  2 18:09:55 pi4 systemd[1]: mopidy.service: Main process exited, code=killed, status=11/SEGV
Sep  2 18:09:55 pi4 systemd[1]: mopidy.service: Failed with result 'signal'.
```
</details>

**Comment by natumbri** [comment]
Thanks @agneevX 

Did you install with this:
```
sudo python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```
or this:
```
agneev@pi4:~ $ sudo python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
```
If it is the second one, are you able to find the file that is generated and saved to `/tmp/` and post it to a gist or similar?

**Comment by agneevX** [comment]
Hey, thanks for getting back.

Well, I installed both. First the "fix", then the whole repo. Both have the same issue. 

In that case, I re-upgraded to `issue-150.zip`.

<details><summary>Install logs</summary>

```bash
agneev@pi4:~ $ sudo python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
  Using cached https://github.com/natumbri/mopidy-youtube/archive/fix/issue-150.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: youtube-dl>=2020.5.3 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (2020.5.29)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (49.6.0)
Requirement already satisfied, skipping upgrade: Mopidy>=3.0 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (3.0.2)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (4.7.1)
Requirement already satisfied, skipping upgrade: cachetools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (4.1.0)
Requirement already satisfied, skipping upgrade: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.0) (2.0.2)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.0) (2.20.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (1.24.3)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.0) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (2019.9.11)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->Mopidy-YouTube==3.0) (2.7)
Building wheels for collected packages: Mopidy-YouTube
  Building wheel for Mopidy-YouTube (PEP 517) ... done
  Created wheel for Mopidy-YouTube: filename=Mopidy_YouTube-3.0-py3-none-any.whl size=26496 sha256=095ef214eb7338934823657aa0bae99f72468cdb067ce57635cb7cf21a4c0367
  Stored in directory: /root/.cache/pip/wheels/df/39/be/50ca706b25181d65718e048da24ae7e1101fef579bdcc8ea63
Successfully built Mopidy-YouTube
Installing collected packages: Mopidy-YouTube
  Attempting uninstall: Mopidy-YouTube
    Found existing installation: Mopidy-YouTube 3.1
    Uninstalling Mopidy-YouTube-3.1:
      Successfully uninstalled Mopidy-YouTube-3.1
Successfully installed Mopidy-YouTube-3.0
```
</details>

Gist: https://gist.github.com/agneevX/b59f64d8039db75b7ab3f246c9110df7

**Comment by natumbri** [comment]
Ok - thanks! I'll investigate and get back to you. Might take a few days - I'm a bit flat out at the moment. 

Have you tried the YouTube Music fork at all? Might not be relevant to this, but maybe have a look at it, if you have the time/inclination.

**Comment by agneevX** [comment]
> Have you tried the YouTube Music fork at all? 

Wasn't sure there was one. Think it's helpful for live videos?

**Comment by natumbri** [comment]
I haven't really looked into it - uses a different API, so might make a difference. It's still pretty beta, but it seems to basically work.

**Comment by agneevX** [comment]
Yeah that also exhibits similar or same behavior..

Part of the log...

```bash
Sep 05 21:20:18 pi4 mopidy[30021]:     for result in cls.run_search(r)
Sep 05 21:20:18 pi4 mopidy[30021]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_bs4api.py", line 60, in run_search
Sep 05 21:20:18 pi4 mopidy[30021]:     return jAPI.json_to_items(cls, result_json)
Sep 05 21:20:18 pi4 mopidy[30021]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_japi.py", line 111, in json_to_items
Sep 05 21:20:18 pi4 mopidy[30021]:     logger.warn("no video-time, possibly live: ", e)
Sep 05 21:20:18 pi4 mopidy[30021]: Message: 'no video-time, possibly live: '
Sep 05 21:20:18 pi4 mopidy[30021]: Arguments: (KeyError('lengthText'),)
Sep 05 21:20:18 pi4 mopidy[30021]: INFO     [YouTubeBackend-3] mopidy_youtube youtube PlaybackProvider.translate_uri "youtube:video/lofi hip hop r
Sep 05 21:20:21 pi4 systemd[1]: mopidy.service: Main process exited, code=killed, status=11/SEGV
Sep 05 21:20:21 pi4 systemd[1]: mopidy.service: Failed with result 'signal'.
```

**Comment by natumbri** [comment]
`IiCpDP0zclY` is NLA on youtube.  If there are other videos that still have this issue with the current version, please let me know.
